### ISSUE TITLE
ISPC error when building embree

### ISSUE THREAD

**Issue by mboisson** [embree/embree#293]
Hi,
While compiling Embree, it fails due to an error with ISPC : 

```
[ 91%] Building ISPC object /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry//triangle_geometry_device.dev.o
cd /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry && /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/cmake -E make_directory /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry/
cd /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry && /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/ispc/1.13.0/bin/ispc -I /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/embree-3.11.0/tutorials/triangle_geometry -DTASKING_TBB --arch=x86-64 --addressing=32 -O3 --target=sse2,sse4,avx,avx2,avx512skx-i32x16 --woff --    opt=fast-math --pic -h /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry/triangle_geometry_device_ispc.h -MMM /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry//triangle_geometry_device.dev.idep -o /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/triangle_geometry//          triangle_geometry_device.dev.o /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/embree-3.11.0/tutorials/triangle_geometry/triangle_geometry_device.ispc
ispc: /tmp/ebuser/avx2/Clang/9.0.1/GCCcore-9.3.0/llvm-9.0.1.src/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:4633: llvm::SDValue llvm::SelectionDAG::getNode(unsigned int, const llvm::SDLoc &, llvm::EVT, llvm::SDValue, const llvm::SDNodeFlags): Assertion `VT.isVector() && !Operand.getValueType().isVector() && (VT.getVectorElementType() == Operand.getValueType() ||  (VT.getVectorElementType().isInteger() && Operand.getValueType().isInteger() && VT.getVectorElementType().bitsLE(Operand.getValueType()))) && "Illegal SCALAR_TO_VECTOR node!"' failed.
/tmp/ebuser/avx2/ispc/1.13.0/system-system/ispc-1.13.0/src/main.cpp(364): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/bin/sh: line 1:  2495 Aborted                 /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/ispc/1.13.0/bin/ispc -I /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/embree-3.11.0/tutorials/closest_point -DTASKING_TBB --arch=x86-64 --addressing=32 -O3 --target=sse2,sse4,avx,avx2,avx512skx-i32x16 --woff --opt=fast-math --pic -h /tmp/mboisson/avx2/Embree/3. 11.0/GCC-9.3.0/easybuild_obj/tutorials/closest_point/closest_point_device_ispc.h -MMM /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/closest_point//closest_point_device.dev.idep -o /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/easybuild_obj/tutorials/closest_point//closest_point_device.dev.o /tmp/mboisson/avx2/Embree/3.11.0/GCC-9.3.0/embree-3.  11.0/tutorials/closest_point/closest_point_device.ispc
``` 

Any idea ?

**Comment by mboisson** [comment]
I think this is related to ISPC 1.13.0. It seems to build with ISPC 1.12.0.

**Comment by freibold** [comment]
Hi,

we have ISPC 1.13 running in our internal testing suite. Which OS are you using?

**Comment by mboisson** [comment]
We use environment modules on an HPC cluster. ISPC 1.13.0 was compiled from source using EasyBuild.

**Comment by freibold** [comment]
Can you test with the prebuilt ispc binaries? Or are they incompatible with your environment?

**Comment by mboisson** [comment]
I can try, but I tried both the binary and the compilation from source for 1.12.0, and they both worked.

**Comment by mboisson** [comment]
We compile ISPC from source using 
```
-DISPC_INCLUDE_TESTS=0 -DARM_ENABLED=0
``` 
and with a patch to disable 32bit
```
diff -ur ispc-1.13.0.orig/cmake/GenerateBuiltins.cmake ispc-1.13.0/cmake/GenerateBuiltins.cmake
--- ispc-1.13.0.orig/cmake/GenerateBuiltins.cmake	2020-04-23 23:29:06.000000000 -0000
+++ ispc-1.13.0/cmake/GenerateBuiltins.cmake	2020-07-17 16:37:05.693931079 -0000
@@ -328,7 +328,7 @@
         list (APPEND supported_oses "ps4")
     endif()
     message (STATUS "ISPC will be built with support of ${supported_oses} for ${supported_archs}")
-    foreach (bit 32 64)
+    foreach (bit 64)
         foreach (os_name "windows" "linux" "freebsd" "macos" "android" "ios" "ps4" "web")
             foreach (arch "x86" "arm" "wasm32")
                 builtin_to_cpp(${bit} ${os_name} ${arch} "${supported_archs}" "${supported_oses}" res${bit}${os_name}${arch})
``` 


Could either be the source of the issue ?

**Comment by freibold** [comment]
Well, in your logs it says that you use --addressing=32 when compiling Embree. That might be the issue.

**Comment by mboisson** [comment]
Ahh!. I'm not sure why we disable that. I'll check with the person who installed ispc.

**Comment by freibold** [comment]
Your can try running cmake with -DEMBREE_ISPC_ADRESSING=64, or edit the value directly in CMakeCache.txt in your build folder.

**Comment by mboisson** [comment]
Thanks. I'll try that and let you know if it fixes the issues (it should).

**Comment by mboisson** [comment]
I confirm that building using the binary version of ISPC works, so it must be the patch for 32bit. I'm now trying with `-DEMBREE_ISPC_ADRESSING=64`

**Comment by jeffamstutz** [comment]
Quick question: are you using the ISPC bindings in your application? If not, you can skip all of this and disable building with ISPC altogether (`-DEMBREE_ISPC_SUPPORT=OFF`).

The reason I ask is that 64-bit addressing has performance implications and will likely require your ISPC code that interfaces with Embree to also be compiled with 64-bit addressing enabled.

**Comment by mboisson** [comment]
I compile Embree because it is a requirement for OSPRAY, which we want to enable to compile ParaView (talk about a walk in the rabbit hole of dependencies...)

**Comment by jeffamstutz** [comment]
Ah, good answer then! ;)

@dbabokin any insight into the original compile error?

**Comment by mboisson** [comment]
Ok, the reason we disabled 32bit is because we don't have the 32bit stubs.h on our system, so compiling ISPC with 32bit support didn't work

**Comment by dbabokin** [comment]
I can't find similar fail in our issue tracker, but I think I've seen something like this.

I see that LLVM 9.0.1 was used. While we support it, we recommend using patched version of LLVM 10.0. This is probably the reason of the fail.

Was in compiled with our script of some pre-built LLVM package was used (this might cause problems).

@DeepakRajendrakumaran Does it look familiar to you?
```code
lib/CodeGen/SelectionDAG/SelectionDAG.cpp:4633: llvm::SDValue llvm::SelectionDAG::getNode(unsigned int, const llvm::SDLoc &, llvm::EVT, llvm::SDValue, const llvm::SDNodeFlags): Assertion `VT.isVector() && !Operand.getValueType().isVector() && (VT.getVectorElementType() == Operand.getValueType() ||  (VT.getVectorElementType().isInteger() && Operand.getValueType().isInteger() && VT.getVectorElementType().bitsLE(Operand.getValueType()))) && "Illegal SCALAR_TO_VECTOR node!"' failed.
/tmp/ebuser/avx2/ispc/1.13.0/system-system/ispc-1.13.0/src/main.cpp(364): FATAL ERROR: Unhandled signal sent to process; terminating.
```

**Comment by DeepakRajendrakumaran** [comment]
There have been some patches ported from llvm dealing with crashes in SelctionDag. But I cannot find anything that seem related to this.

**Comment by cbenthin** [comment]
Seems to be more of an ISPC build issue. Closing it for now.
