### ISSUE TITLE
INT_MIN was not declared, missing #include <limits.h> in bvh_traverser1.h

### ISSUE THREAD

**Issue by Speierers** [embree/embree#277]
Hi,

I am getting the following compiler error with gcc (GCC) 8.3.0 on Red Hat 7.6:

```
.../embree/kernels/bvh/bvh_traverser1.h:501:20: error: ‘INT_MIN’ was not declared in this scope
         vint8 dist(INT_MIN); // this will work with -0.0f (0x80000000) as distance, isort_update uses >= to insert
                    ^~~~~~~
.../embree/kernels/bvh/bvh_traverser1.h:501:20: note: ‘INT_MIN’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
.../embree/kernels/bvh/bvh_traverser1.h:23:1:
+#include <climits>
```

Is it possible that the `<limits.h>` or `<climits>` include is simply missing?

Thanks!

**Comment by svenwoop** [comment]
Yes, please add climits include to the common/math/constants.h file. We will fix this in the next release.
